spring.application.name=reservationbooking

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/springbootdb
spring.datasource.username=postgres
spring.datasource.password=postgres@123
spring.datasource.driver-class-name=org.postgresql.Driver

# Connection Pool Settings
spring.datasource.testWhileIdle=true
spring.datasource.validationQuery=SELECT 1

# JPA / Hibernate Settings
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Initialization Scripts
spring.datasource.initialization-mode=always
spring.datasource.schema=classpath:/schema.sql
spring.datasource.data=classpath:/data.sql

# Error Handling
spring.datasource.continue-on-error=true
