export const FETCH_SEATS_REQUEST = 'FETCH_SEATS_REQUEST';
export const FETCH_SEATS_SUCCESS = 'FETCH_SEATS_SUCCESS';
export const FETCH_SEATS_FAILURE = 'FETCH_SEATS_FAILURE';
export const SELECT_SEAT = 'SELECT_SEAT';