export const SET_TRANSPORT_SEATS = 'SET_TRANSPORT_SEATS';
export const SET_TRANSPORT_SEATS_ERROR = 'SET_TRANSPORT_SEATS_ERROR';
export const SET_LOADING = 'SET_LOADING';
export const SELECT_TRANSPORT_SEAT = 'SELECT_TRANSPORT_SEAT'; 
